[workspace]
members = [ 
    "fpv-freq-ui"
]
resolver = "2"

[workspace.dependencies]
tracing = { version = "0.1", features = [] }
tracing-subscriber = { version = "0.3", features = [] }

anyhow = "1.0"

serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"

[workspace.lints.rust]
rust_2018_idioms = "deny"
# missing_docs = "deny"
missing_debug_implementations = "allow"
future_incompatible = "deny"
unsafe-code = "deny"

[workspace.lints.clippy]
unused_async = "deny"
pedantic = "warn"